# Generated by Django 4.0.4 on 2022-04-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_listings', '0002_book_listing_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_listing',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
