# Generated by Django 4.0.4 on 2022-05-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_listings', '0003_alter_book_listing_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_listing',
            name='category',
            field=models.CharField(choices=[('FICTION', 'Fiction'), ('LITERATURE', 'Literature'), ('HISTORY', 'History'), ('PHYSICS', 'Physics'), ('MATH', 'Math'), ('COMPUTER_SCIENCE', 'Computer Science')], default='COMPUTER_SCIENCE', max_length=50),
        ),
    ]
